#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["race-01/race-01.csproj", "race-01/"]
RUN dotnet restore "race-01/race-01.csproj"
COPY . .
WORKDIR "/src/race-01"
RUN dotnet build "race-01.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "race-01.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "race-01.dll"]